import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import OthFETeam from './oth-fe-team'
const teamMembers=[{
  id:1,
  name:'Chad Clayton',
  title:'Product manager'
},
{
  id:2,
  name:'Eric fieldman',
  title:'Developer'
},
{
  id:3,
  name:'Madhu Payyavula',
  title:'Developer'
},
{
  id:4,
  name:'Monisha Rajendran',
  title:'Developer'
},
{
  id:5,
  name:'Eric Feldman',
  title:'Developer'
},
{
  id:6,
  name:'Eric Feldman',
  title:'Developer'
},
{
  id:7,
  name:'Jay Bohra',
  title:'Developer'
},
{
  id:8  ,
  name:'Ankit Sengupta',
  title:'Developer'
},

]
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OTH Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-24">
  <div className="text-center mb-16">
    <p className="mt-4 text-sm leading-7 text-gray-500 font-regular">
        THE OTH TEAM
      </p>
      <h3 className="text-3xl sm:text-4xl leading-normal font-extrabold tracking-tight text-gray-900">
        Meet Our <span className="text-indigo-600">Team</span>
      </h3>
  </div>
  
  
  <div className="grid gap-4 grid-cols-3 grid-rows-3">

  {teamMembers.map(member=><OthFETeam key={member? member.id:""} results={member}></OthFETeam>)}  
    </div>  
    
  </div>
  



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
