import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import OthFETeam from './oth-fe-team'
const teamMembers=[{
  name:'Chad Clayton',
  title:'Product manage'
},
{
  name:'Eric fieldman',
  title:'Developer'
},
{
  name:'Madhu Payyavula ',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
{
  name:'Eric Feldman',
  title:'Developer'
},
]
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>OTH Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="p-24">
  <div class="text-center mb-16">
    <p class="mt-4 text-sm leading-7 text-gray-500 font-regular">
        THE OTH TEAM
      </p>
      <h3 class="text-3xl sm:text-4xl leading-normal font-extrabold tracking-tight text-gray-900">
        Meet Our <span class="text-indigo-600">Team</span>
      </h3>
  </div>
  
  
  <div class="grid gap-4 grid-cols-3 grid-rows-3">

  {teamMembers.map(member=><OthFETeam  results={member}></OthFETeam>)}  
    </div>  
    
  </div>
  



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
